### ISSUE TITLE
[v3_2_3_0] ApplicationPolicy.get_application_sets repointed from /v1/ to /v2/ and gained required arguments

### ISSUE THREAD

**Issue by phamchidat** [cisco-en-programmability/catalystcentersdk#59]
**Prerequisites**

* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest SDK version? (3.2.3.0.0)
* [x] Review the compatibility matrix before opening an issue.

**Describe the bug**

After upgrading from `catalystcentersdk` 3.1.6.0.7 to 3.2.3.0.0 against Catalyst
Center 3.2.3, existing calls to `get_application_sets` fail:

```
ApplicationPolicy.get_application_sets() missing 3 required positional arguments:
'attributes', 'limit', and 'offset'
```

The method was repointed from `/dna/intent/api/v1/` to `/dna/intent/api/v2/` and
inherited the v2 endpoint's mandatory arguments:

```python
import inspect
from catalystcentersdk.api.v3_1_6_0.application_policy import ApplicationPolicy as AP316
from catalystcentersdk.api.v3_2_3_0.application_policy import ApplicationPolicy as AP323

print(inspect.signature(AP316.get_application_sets))
# (self, limit=None, name=None, offset=None, headers=None, **request_parameters)
#   -> GET /dna/intent/api/v1/application-policy-application-set

print(inspect.signature(AP323.get_application_sets))
# (self, attributes, limit, offset, name=None, headers=None, **request_parameters)
#   -> GET /dna/intent/api/v2/application-policy-application-set
```

The previous behaviour still exists, but under a new name, `get_application_sets_v1`.
The established name was handed to what used to be `get_application_sets_v2`.

**The v2 endpoint was already reachable before this change**

3.1.6.0.7 already exposed the v2 endpoint under an explicit name:

```
3.1.6.0.7 / v3_1_6_0:
  get_application_sets      -> /dna/intent/api/v1/application-policy-application-set
  get_application_sets_v2   -> /dna/intent/api/v2/application-policy-application-set
```

Callers who wanted v2 semantics could already request them by name. Repointing the
bare name therefore made no new capability available — it only changed the meaning of
a name that existing callers depend on, and it did so without an alias or a
deprecation period.

In 3.2.3.0.0 the suffix no longer selects a version either: `get_application_sets_v2`
is now an alias for `get_application_sets`. So there is currently no name that
reliably means "v2" and no name that still means what `get_application_sets` meant in
3.1.6.0.7.

**Expected behavior**

1. `get_application_sets` restored to its 3.1.6.0.7 behaviour (v1, all arguments
   optional), with the v2 endpoint remaining available as `get_application_sets_v2` as
   it already was. Alternatively, if the repointing is intended, `attributes`, `limit`
   and `offset` given defaults so existing call sites keep working.
2. The rename and the endpoint change listed in the release notes. An endpoint change
   is easy to miss because it does not always raise.

**Screenshots**

Both endpoints behave correctly on the controller — this is a Python binding issue:

```bash
curl -k -X GET \
  "https://<cc-host>/dna/intent/api/v1/application-policy-application-set?name=collaboration-apps" \
  -H "X-Auth-Token: <token>"
# -> 200 OK

curl -k -X GET \
  "https://<cc-host>/dna/intent/api/v2/application-policy-application-set?attributes=applicationSet&offset=1&limit=500" \
  -H "X-Auth-Token: <token>"
# -> 200 OK
```

**Environment (please complete the following information):**

* Cisco Catalyst Center Version and patch: 3.2.3-75345
* Python version: 3.12.0
* SDK version: 3.2.3.0.0 (upgraded from 3.1.6.0.7)
* OS Version: Red Hat Enterprise Linux 8.10 (Ootpa), kernel 4.18.0-553.155.1.el8_10

**Additional context**

3.1.6.0.7 ships no `v3_2_3_0` namespace, so managing a 3.2.3 controller requires the
upgrade; the comparison above is between 3.1.6.0.7/`v3_1_6_0` and
3.2.3.0.0/`v3_2_3_0`, which is the transition an existing deployment experiences.

Downstream impact in `cisco.catalystcenter` 2.10.2 — two call sites in
`plugins/modules/application_policy_workflow_manager.py`
(`get_application_set_details()` and `get_application_set_id()`) call
`get_application_sets` with `{"name": name}` and now raise `TypeError`.
`plugins/modules/application_policy_playbook_config_generator.py` is affected by the
same change.

Secondary observation, from reading the source rather than from an observed failure:
`delete_application_set` was repointed the same way — `/v1/...?id=<id>` in 3.1.6.0.7
to `/v2/.../{id}` in 3.2.3.0.0 — while its signature stayed byte-for-byte identical
(`(self, id, headers=None, **request_parameters)`). Existing callers keep running
without any error, so if the two endpoints ever differ in behaviour the change would
be invisible to them. I have not observed a failure from this and am noting it only
because a signature diff would not reveal it.
