### ISSUE TITLE
[v3_2_3_0] Sda: the get_port_channels backward-compatibility alias was dropped

### ISSUE THREAD

**Issue by phamchidat** [cisco-en-programmability/catalystcentersdk#65]
**Prerequisites**

* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest SDK version?
* [x] Review the compatibility matrix before opening an issue.

**Describe the bug**

After upgrading `catalystcentersdk` from 3.1.6.0.7 to 3.2.3.0.0 against Catalyst
Center 3.2.3:

```
'Sda' object has no attribute 'get_port_channels'
```

`get_port_channels` was never a distinct API call — it is a backward-compatibility
alias for `get_port_channels_connectivity`, declared at the end of
`3.1.6.0.7/v3_1_6_0/sda.py` (line 10322):

```python
# Alias Functions
Sda.get_port_channels = Sda.get_port_channels_connectivity
```

`3.2.3.0.0/v3_2_3_0/sda.py` contains no `# Alias Functions` block at all, and no
definition or assignment of `get_port_channels`. The alias target is unchanged and
still present, so no functionality was removed — only the compatibility entry point.

**The rest of the port-channel family is untouched**

Every other port-channel method survived the transition:

| method | 3.1.6.0.7 | 3.2.3.0.0 |
|---|---|---|
| `get_port_channels_connectivity` | present | present |
| `add_port_channels` | present | present |
| `update_port_channels` | present | present |
| `delete_port_channels` | present | present |
| `get_port_channel_count` | present | present |
| `delete_port_channel_by_id` | present | present |
| `get_port_channels` | present (alias) | **absent** |

Only the alias disappeared, which is what makes this look like an oversight rather
than a deprecation.

**Reproduction**

```python
import importlib

for v in ["v2_3_7_9", "v3_1_3_0", "v3_1_6_0", "v3_2_3_0"]:
    C = getattr(importlib.import_module(f"catalystcentersdk.api.{v}.sda"), "Sda")
    print(f"{v:10} get_port_channels={hasattr(C, 'get_port_channels')!s:6} "
          f"get_port_channels_connectivity={hasattr(C, 'get_port_channels_connectivity')}")
```

Output on `catalystcentersdk` 3.2.3.0.0:

```
v2_3_7_9   get_port_channels=True   get_port_channels_connectivity=True
v3_1_3_0   get_port_channels=True   get_port_channels_connectivity=True
v3_1_6_0   get_port_channels=True   get_port_channels_connectivity=True
v3_2_3_0   get_port_channels=False  get_port_channels_connectivity=True
```

Note that a search for `def get_port_channels` finds nothing even in the namespaces
that expose it, because the alias is created by assignment rather than by definition.
`hasattr` on the imported class is the reliable check.

**Expected behavior**

`Sda.get_port_channels` restored in `v3_2_3_0` as an alias for
`get_port_channels_connectivity`. The target still exists in the same namespace, so
the alias costs nothing at runtime and the change is a single line.

This would match the precedent set by
[PR #47](https://github.com/cisco-en-programmability/catalystcentersdk/pull/47)
(25 backward-compatibility aliases added in v3.1.6.0.7) and
[PR #41](https://github.com/cisco-en-programmability/catalystcentersdk/pull/41)
(7 Site Design aliases added, from
[issue #39](https://github.com/cisco-en-programmability/catalystcentersdk/issues/39)).

It may also be worth adding a generator-pipeline check that fails the build when a
name published in a previous namespace is absent from the next one.

**Screenshots**

Not applicable — no REST endpoint is involved. The alias delegates to
`get_port_channels_connectivity`, which is present and working in the same namespace;
the defect is entirely in the Python bindings and is demonstrated by the output above.

**Environment (please complete the following information):**

* Cisco Catalyst Center Version and patch: 3.2.3-75345
* Python version: 3.12.0
* SDK version: 3.2.3.0.0 (upgraded from 3.1.6.0.7)
* OS Version: Red Hat Enterprise Linux 8.10 (Ootpa), kernel 4.18.0-553.155.1.el8_10

**Additional context**

3.1.6.0.7 ships no `v3_2_3_0` namespace, so managing a 3.2.3 controller requires the
upgrade; the comparison above is between 3.1.6.0.7/`v3_1_6_0` and
3.2.3.0.0/`v3_2_3_0`, which is the transition an existing deployment experiences.

Downstream impact in `cisco.catalystcenter` 2.10.2 — six files call this method:

* `plugins/modules/sda_host_port_onboarding_workflow_manager.py`
* `plugins/modules/sda_host_port_onboarding_playbook_config_generator.py`
* `plugins/modules/fabric_devices_info_workflow_manager.py`
* `plugins/modules/lan_automation_workflow_manager.py`
* `plugins/action/lan_automation_port_channels.py`
* `plugins/action/lan_automation_port_channels_info.py`

Related: #62 reports the same pattern in `UserAndRoles` — a trailing
`# Alias Functions` block present in 3.1.6.0.7 and absent from `v3_2_3_0`.
